development:
  secret_key_base: here_goes_my_secret_key_base
  google_client_id: 690420652745-1mc7gv23s51hf2rh7hf6f2rfs3cj8u6m.apps.googleusercontent.com
  google_client_secret: -VNlqjNVqVu1EaKKU2b_p4ZN

test:
  secret_key_base: here_goes_my_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>